name: Build and Test

# This workflow will run on any push to the repository
on: push

jobs:
  test:
    # Set up a virtual machine to run our tests
    runs-on: ubuntu-latest

    steps:
      # Step to check out the code
      - name: Check out the code
        uses: actions/checkout@v3

      # Set up the desired Python version
      - name: Set up Python 3.11.0
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.0

      # Set up venv, install dependencies from requirements.txt, and upgrade pip
      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run tests with pytest
      - name: Test with pytest
        run: |
          source venv/bin/activate
        
